-- Asil Kuyumcu Pro V5 - SQL hedef şeması (PostgreSQL uyumlu)
CREATE TABLE fiscal_periods (id bigserial primary key, year int unique not null, status varchar(20) default 'OPEN', closed_at timestamptz);
CREATE TABLE users (id text primary key, username text unique not null, display_name text, role text, password_hash text, active boolean default true);
CREATE TABLE customers (id text primary key, code text, name text not null, account_type text, accounting_nature text, phone text, email text, tax_no text, created_at timestamptz default now());
CREATE TABLE stock_cards (id text primary key, code text unique, name text not null, product_type text, product_group text, purity numeric(10,4), unit text, standard_gram numeric(14,4), workmanship_type text);
CREATE TABLE stock_items (id text primary key, period_year int, stock_card_id text references stock_cards(id), barcode text unique, rfid text, status text, gram numeric(16,4), physical_has numeric(16,6), cost_has numeric(16,6), sale_has numeric(16,6), location text, supplier_id text references customers(id), extra jsonb default '{}'::jsonb);
CREATE TABLE transactions (id text primary key, doc_no text unique not null, period_year int, txn_type text not null, status text default 'ACTIVE', txn_date timestamptz default now(), user_id text, description text, reversed_txn_id text references transactions(id));
CREATE TABLE transaction_entries (id bigserial primary key, transaction_id text references transactions(id) on delete cascade, module text not null, entity_id text, account_id text, unit text, debit numeric(20,6) default 0, credit numeric(20,6) default 0, amount_tl numeric(20,2) default 0, meta jsonb default '{}'::jsonb);
CREATE TABLE sales (id text primary key, transaction_id text references transactions(id), doc_no text unique, period_year int, customer_id text references customers(id), salesperson_id text, total_tl numeric(20,2), revenue_has numeric(20,6), cost_has numeric(20,6), status text, created_at timestamptz default now());
CREATE TABLE sale_lines (id bigserial primary key, sale_id text references sales(id) on delete cascade, stock_item_id text references stock_items(id), stock_card_id text references stock_cards(id), quantity numeric(16,4), unit text, unit_price_tl numeric(20,2), total_tl numeric(20,2), sale_has numeric(20,6), cost_has numeric(20,6));
CREATE TABLE payments (id bigserial primary key, transaction_id text references transactions(id), payment_type text, account_id text, unit text, native_amount numeric(20,6), tl_amount numeric(20,2), commission_tl numeric(20,2) default 0, value_date date);
CREATE TABLE customer_ledger (id bigserial primary key, transaction_id text references transactions(id), customer_id text references customers(id), unit text, debit numeric(20,6) default 0, credit numeric(20,6) default 0, created_at timestamptz default now());
CREATE TABLE finance_accounts (id text primary key, name text not null, account_type text, currency text, balance numeric(20,6) default 0, bank_name text, commission_rate numeric(9,4) default 0, value_days int default 0);
CREATE TABLE finance_ledger (id bigserial primary key, transaction_id text references transactions(id), account_id text references finance_accounts(id), direction text, unit text, native_amount numeric(20,6), tl_amount numeric(20,2), created_at timestamptz default now());
CREATE TABLE special_products (id text primary key, stock_item_id text references stock_items(id), product_type text, brand text, model text, serial_no text, certificate_no text, carat numeric(12,4), color text, clarity text, photo_url text, extra jsonb default '{}'::jsonb);
CREATE TABLE audit_log (id bigserial primary key, transaction_id text, user_id text, module text, action text, created_at timestamptz default now(), meta jsonb default '{}'::jsonb);
CREATE INDEX idx_txn_period_date ON transactions(period_year, txn_date);
CREATE INDEX idx_stock_status_period ON stock_items(period_year, status);
CREATE INDEX idx_customer_ledger_customer ON customer_ledger(customer_id, created_at);
